# Generated by Django 5.2.8 on 2025-11-11 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_content', models.TextField(help_text='Content of the message before the edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Message histories',
                'db_table': 'message_history',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Parent message for threaded conversations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chats.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been read by the receiver'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Direct recipient of the message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='guest', max_length=10),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'read'], name='messages_receive_0a8061_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message'], name='messages_parent__8cda5e_idx'),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_by',
            field=models.ForeignKey(help_text='User who made the edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='message',
            field=models.ForeignKey(help_text='The message that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='chats.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(help_text='Message that triggered the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chats.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagehistory',
            index=models.Index(fields=['message', 'edited_at'], name='message_his_message_13e95c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
